import { Quiz } from '../components/Quiz'
import type { QuizQuestion } from '../components/Quiz'
import { useMarkVisited } from '../hooks/useMarkVisited'
import { NextLesson } from '../components/NextLesson'
import { LessonNote } from '../components/LessonNote'
import { CompletedBadge } from '../components/CompletedBadge'
import { RelatedLessons } from '../components/RelatedLessons'
import { LessonRating } from '../components/LessonRating'
import { LessonFeedback } from '../components/LessonFeedback'
import { ReviewLaterButton } from '../components/ReviewLaterButton'
import { ShareButton } from '../components/ShareButton'
import { KeyTakeaways } from '../components/KeyTakeaways'

const LESSON_TITLE = 'AI and sport betting — algorithmic odds, AI trading bots, in-play betting, and addiction profiling'

const KEY_TAKEAWAYS = [
  'Bookmakers like Bet365 and Sky Bet use AI to calculate and adjust odds in real time, processing thousands of data points far faster than any human trader could.',
  'Betfair\'s Exchange is dominated by automated AI trading bots — ordinary punters are often competing against algorithms rather than other humans.',
  'In-play betting uses AI to update odds within milliseconds of a match event — a goal, red card, or injury triggers instant repricing across all markets.',
  'AI systems in betting apps analyse user behaviour to identify both high-value customers (for promotions) and at-risk gamblers (who UK law requires firms to treat with care).',
  'The 2023 UK Gambling White Paper proposed reforms including affordability checks and deposit limits — the industry is using AI to implement compliance while also continuing to use it for commercial targeting.',
]

const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    question: 'How do bookmakers like Bet365 and Sky Bet use AI to set odds?',
    options: [
      'Human traders set all odds manually, with AI used only to check their calculations for errors',
      'AI processes thousands of real-time data points — team news, weather, form, market sentiment, betting volumes — to calculate probabilities and automatically adjust odds far faster than any human',
      'All UK bookmakers use the same AI system provided by the UK Gambling Commission to ensure consistent odds across the industry',
      'AI is only used for less popular markets — all football and horse racing odds are still set by human traders',
    ],
    correctIndex: 1,
    explanation:
      'Modern bookmaking is almost entirely automated. AI models process real-time data from multiple sources — team news, injury reports, historical form, weather conditions, betting patterns from other markets globally — to calculate implied probabilities and set prices. When a major team announces an injury, the odds update within seconds. This speed advantage is one reason why professional gamblers find it increasingly difficult to find value in bookmaker markets.',
  },
  {
    question: 'What are AI trading bots on the Betfair Exchange, and why do they matter for ordinary punters?',
    options: [
      'Betfair\'s trading bots are customer service chatbots that help users navigate the platform',
      'Trading bots are automated algorithms that bet and trade on the Exchange matching engine at high speed, meaning ordinary customers are often competing against sophisticated automated systems rather than other human punters',
      'Trading bots are used by Betfair to ensure there is always liquidity in every market, acting as a guaranteed market maker',
      'Trading bots on Betfair are illegal and have been banned by the UK Gambling Commission since 2020',
    ],
    correctIndex: 1,
    explanation:
      'Betfair Exchange is a peer-to-peer betting marketplace where customers bet against each other rather than against the bookmaker. A significant proportion of the volume on the Exchange is generated by automated trading bots — algorithms that place and trade bets at very high speed, exploiting tiny price discrepancies. For ordinary punters, this creates an uneven playing field: you are not just competing with other human bettors, but with sophisticated algorithmic systems that can react to new information in milliseconds.',
  },
  {
    question: 'How does in-play betting use AI to update odds during a live match?',
    options: [
      'Odds during in-play betting are frozen when a significant event occurs and only updated during natural breaks in play',
      'AI systems monitor live match data feeds (goals, red cards, injuries, possession, shots on target) and reprice all affected markets within milliseconds of an event being reported',
      'In-play odds are set by a team of human traders watching the match who adjust prices manually using tablets on a trading floor',
      'In-play betting is powered by the same AI as pre-match betting — no special real-time systems are needed',
    ],
    correctIndex: 1,
    explanation:
      'In-play (live) betting requires AI systems that can process live match data feeds and rapidly reprice all markets — match result, next goalscorer, Asian handicaps, total goals, and dozens of others — within milliseconds of a significant event. A goal being scored might require simultaneous repricing of hundreds of markets. The latency between an event happening and the odds updating is now measured in milliseconds, driven by dedicated real-time AI pricing engines.',
  },
  {
    question: 'How do AI systems in betting apps identify at-risk gamblers, and what does UK law require firms to do?',
    options: [
      'UK law does not require betting firms to identify problem gamblers — this is entirely voluntary',
      'AI analyses behavioural signals (deposit frequency, chasing losses, session length, response to losing) to identify customers showing signs of problem gambling — UK law under the Gambling Act and LCCP requires firms to interact with and protect at-risk customers',
      'AI is only used to identify at-risk gamblers for the purpose of offering them self-exclusion options; no other commercial use of this data is permitted',
      'At-risk gamblers are identified through mandatory self-reporting via annual surveys that all registered customers must complete',
    ],
    correctIndex: 1,
    explanation:
      'The UK Gambling Act and the Gambling Commission\'s Licence Conditions and Codes of Practice (LCCP) require betting operators to identify customers showing signs of problem gambling and take proportionate action — ranging from a welfare check message to account restrictions or closure. Operators use AI to analyse behavioural markers: unusual deposit patterns, chasing losses, gambling during unusual hours, high session frequency. The same AI systems that identify at-risk customers are also used to identify high-value customers for promotions — a tension the 2023 Gambling White Paper sought to address through stricter affordability checks.',
  },
  {
    question: 'What did the UK government\'s 2023 Gambling White Paper propose to address AI-driven harm in betting?',
    options: [
      'It proposed banning all AI from the betting industry and requiring human traders to set all odds manually',
      'It proposed measures including mandatory affordability checks for customers spending above certain thresholds, deposit limits, and new requirements on operators to use their data systems to identify and protect at-risk gamblers',
      'It proposed a publicly owned gambling exchange to replace commercial bookmakers and ensure all profits went to public health',
      'It proposed no new requirements, finding that existing AI-based responsible gambling tools were sufficient',
    ],
    correctIndex: 1,
    explanation:
      'The UK Gambling White Paper (April 2023) was the first major review of gambling regulation since the Gambling Act 2005. Key proposals included: mandatory frictionless affordability checks for customers spending over defined thresholds; maximum stake limits for online slots; requirements for operators to proactively identify and contact at-risk customers; and enhanced powers for the Gambling Commission. The paper acknowledged that operators\' AI systems could and should be used for consumer protection as well as commercial purposes. Implementation was still ongoing as of 2024.',
  },
]

export function AIAndSportBetting() {
  useMarkVisited('ai-and-sport-betting')

  return (
    <div className="max-w-3xl mx-auto px-4 py-10">
      <h1 className="text-3xl font-bold text-gray-900 dark:text-gray-100 mb-2">{LESSON_TITLE}</h1>
      <p className="text-gray-500 dark:text-gray-400 text-sm mb-6">8 min read &middot; Intermediate</p>

      <CompletedBadge lessonId="ai-and-sport-betting" />
      <ShareButton lessonTitle={LESSON_TITLE} />

      <KeyTakeaways points={KEY_TAKEAWAYS} />

      <div className="prose prose-gray dark:prose-invert max-w-none mt-8">

        <h2>The invisible infrastructure of modern betting</h2>
        <p>
          When you place a bet on a football match, the odds you see are not set by a person sitting at a desk watching the game. They are calculated by AI systems processing thousands of data points &mdash; historical results, current form, team news, weather conditions, global market sentiment, and the real-time betting volumes on your own platform and others &mdash; and updating continuously.
        </p>
        <p>
          The UK gambling industry generates around &pound;15 billion in gross gambling yield annually. AI sits at the heart of almost every part of it: setting prices, managing risk, targeting promotions, and increasingly, attempting to identify problem gamblers before harm escalates.
        </p>

        <h2>How AI sets betting odds</h2>
        <p>
          A bookmaker&apos;s core business model involves pricing risk. For every event, they need to set odds that reflect the true probability of outcomes (so they do not lose money by pricing things wrong) while also building in a margin (so they make a profit over time). AI has transformed both the accuracy and the speed of this process.
        </p>
        <p>
          Modern odds-setting algorithms at firms like Bet365, Sky Bet, and Ladbrokes process data from dozens of sources simultaneously: injury and team news, referee statistics, historical head-to-head records, current league form, goal timing patterns, and the real-time betting patterns of their own customers. When major new information arrives &mdash; a key player ruled out hours before a match &mdash; prices update within seconds across all affected markets.
        </p>

        <h2>AI trading bots on the Betfair Exchange</h2>
        <p>
          Betfair Exchange is a peer-to-peer betting platform where customers bet against each other rather than against the bookmaker. It has become heavily influenced by automated trading bots &mdash; algorithms that place and trade bets at very high speed, exploiting small price discrepancies.
        </p>
        <p>
          A significant proportion of the liquidity on the Exchange is generated by these bots. This has several effects: it keeps prices tighter and more efficient, which is good for the market overall, but it also means ordinary punters are competing against sophisticated automated systems. A human bettor looking for value in a pre-match market may already be trading against algorithms that have already priced in the same information.
        </p>

        <h2>In-play betting and real-time AI</h2>
        <p>
          In-play betting &mdash; placing bets during a live sporting event &mdash; requires the most technically demanding AI systems in gambling. After a goal is scored, hundreds of markets need repricing simultaneously: the match result, the Asian handicap, the total goals line, next goalscorer markets, and more. This has to happen within milliseconds, before the information becomes publicly visible and arbitrageurs can exploit the stale prices.
        </p>
        <p>
          Live data feeds from official providers (Opta, Stats Perform, BetGenius) deliver real-time match events directly to pricing engines. The AI processes the new information and immediately adjusts every affected market. The time between a goal being flagged in the data feed and the odds updating on a major bookmaker&apos;s platform is typically under a second.
        </p>

        <LessonNote lessonId="ai-and-sport-betting" />

        <h2>Personalisation, promotions, and addiction profiling</h2>
        <p>
          Betting apps use AI to personalise the user experience. Promotional offers are targeted based on your betting history: if you mostly bet on Premier League matches, you will receive offers related to upcoming Premier League fixtures. This targeting is designed to maximise engagement and spending.
        </p>
        <p>
          The same behavioural data that enables commercial targeting is also used &mdash; or should be used &mdash; to identify problem gambling. Patterns like: depositing and immediately losing, then depositing again; gambling at unusual hours; session lengths that suggest distressed play; or responding unusually to losing streaks are signals that an automated monitoring system can detect.
        </p>
        <p>
          UK law under the Gambling Commission&apos;s Licence Conditions and Codes of Practice (LCCP) requires operators to have systems in place to identify at-risk customers and take action. What &ldquo;action&rdquo; means varies from a welfare pop-up message to an account restriction or closure.
        </p>

        <h2>The 2023 Gambling White Paper and reform</h2>
        <p>
          The UK Gambling White Paper of April 2023 was the first major review of gambling regulation since the Gambling Act 2005 &mdash; passed before smartphones existed. Its proposals acknowledged that the gambling landscape had been transformed by technology and that AI-driven personalisation and targeting required new safeguards.
        </p>
        <p>
          Key proposals included mandatory affordability checks for customers spending above defined thresholds, maximum stake limits for online slots, and stronger requirements for operators to use their data to proactively identify and protect at-risk customers. GAMSTOP &mdash; the national self-exclusion register &mdash; remains a key tool, with AI systems required to match customers who self-exclude across all licensed UK operators.
        </p>

      </div>

      <div className="mt-10">
        <Quiz questions={QUIZ_QUESTIONS} lessonId="ai-and-sport-betting" />
      </div>

      <ReviewLaterButton lessonId="ai-and-sport-betting" />
      <LessonRating lessonId="ai-and-sport-betting" />
      <LessonFeedback lessonId="ai-and-sport-betting" />
      <RelatedLessons currentId="ai-and-sport-betting" />
      <NextLesson currentId="ai-and-sport-betting" />
    </div>
  )
}
