import { Quiz } from '../components/Quiz'
import type { QuizQuestion } from '../components/Quiz'
import { useMarkVisited } from '../hooks/useMarkVisited'
import { NextLesson } from '../components/NextLesson'
import { LessonNote } from '../components/LessonNote'
import { CompletedBadge } from '../components/CompletedBadge'
import { RelatedLessons } from '../components/RelatedLessons'
import { LessonRating } from '../components/LessonRating'
import { LessonFeedback } from '../components/LessonFeedback'
import { ReviewLaterButton } from '../components/ReviewLaterButton'
import { ShareButton } from '../components/ShareButton'
import { KeyTakeaways } from '../components/KeyTakeaways'
import { DifficultyBadge } from '../components/DifficultyBadge'

const LESSON_TITLE = 'AI and cybercrime'

const KEY_TAKEAWAYS = [
  'AI has made cyberattacks faster, cheaper, and more convincing — phishing emails generated by AI are now grammatically perfect, personalised, and nearly indistinguishable from genuine messages.',
  'Deepfake audio and video allow criminals to impersonate real people — a technique used to authorise fake bank transfers, access accounts, or spread misinformation.',
  'Ransomware attacks increasingly use AI to identify the most valuable files, choose the best moment to strike, and automate the attack at scale.',
  'The same AI tools that power cyberattacks also power the defences — security software uses AI to spot unusual behaviour, block threats in real time, and respond faster than any human team could.',
  'Staying safe online still comes down to a few key habits: strong unique passwords, two-factor authentication, keeping software updated, and pausing before clicking links.',
]

const quizQuestions: QuizQuestion[] = [
  {
    question: 'How has AI changed phishing emails compared to those sent five years ago?',
    options: [
      'AI has made them shorter and easier to filter automatically',
      'AI has made them harder to spot — they are now grammatically perfect, personalised, and written in your own dialect',
      'AI has had no effect — scammers still use the same generic templates',
      'AI has made them longer, which makes them easier to identify as suspicious',
    ],
    correctIndex: 1,
    explanation:
      'Traditional phishing emails were easy to spot: poor spelling, odd grammar, generic greetings. AI writing tools have eliminated those giveaways. Modern AI-generated phishing messages are fluent, personalised (using your name and employer scraped from social media), and indistinguishable in tone from a genuine email from your bank or HR department. Security researchers have found that AI-generated phishing emails achieve significantly higher click rates than older templates.',
    hint: 'Think about the classic warning signs of a phishing email that no longer apply.',
  },
  {
    question: 'What is a deepfake in the context of cybercrime?',
    options: [
      'A type of malware that hides deep inside your operating system and is very hard to remove',
      'A fake social media profile that uses AI to generate convincing posts over time',
      'AI-generated audio or video that realistically mimics a real person — used to impersonate them in calls, authorise fake transactions, or spread misinformation',
      'A technique where criminals create a fake Wi-Fi hotspot to intercept your data',
    ],
    correctIndex: 2,
    explanation:
      "Deepfake technology can clone a person's voice from a few seconds of audio — from a voicemail, a YouTube video, or a social media clip. It can also generate convincing video of someone saying things they never said. In fraud cases, deepfake voice calls have been used to impersonate CEOs and instruct employees to make urgent bank transfers. In one documented case, a company lost $25 million after criminals used a deepfake video call impersonating the firm's CFO.",
    hint: 'Think about AI generating fake but realistic media.',
  },
  {
    question: 'What does ransomware do, and how is AI making it more dangerous?',
    options: [
      'Ransomware steals your identity and sells it online; AI helps criminals find buyers faster',
      'Ransomware encrypts your files and demands payment to restore them; AI helps attackers identify the most valuable targets and automate the attack at scale',
      'Ransomware floods your internet connection with traffic; AI makes the flood larger and harder to block',
      'Ransomware sends spam from your email address; AI makes the spam more convincing',
    ],
    correctIndex: 1,
    explanation:
      'Ransomware locks you out of your own files by encrypting them, then demands payment (usually in cryptocurrency) for the decryption key. AI helps attackers profile targets in advance, identify the most critical files and systems, choose the optimal time to strike (e.g. a Friday evening when fewer IT staff are on duty), and automate the ransom negotiation. AI has also made ransomware easier to build — criminal groups now sell it as a service, so technically unsophisticated criminals can launch sophisticated attacks.',
    hint: 'Focus on what ransomware does to your files, then think about how AI improves each step.',
  },
  {
    question: 'How do cybersecurity defenders use AI to fight back against AI-powered attacks?',
    options: [
      'They use AI to completely block all foreign network traffic, preventing attacks from outside the country',
      'They use AI to monitor user behaviour and network traffic in real time, detect anomalies that suggest an attack, and respond in milliseconds — far faster than a human security team',
      'They use AI to create legal documents and prosecute cybercriminals more quickly',
      'They use AI to scan the dark web and report criminals to the police automatically',
    ],
    correctIndex: 1,
    explanation:
      "AI-powered security tools like Microsoft Defender, CrowdStrike, and Darktrace learn what normal looks like on your network — typical login times, usual file access patterns, normal amounts of data being transferred. When something deviates (an account logging in from an unusual country at 3am, or suddenly accessing thousands of files), the AI flags it or blocks it automatically. Because attacks can unfold in seconds, human-speed responses are not fast enough — AI defences that can react in milliseconds are increasingly essential.",
    hint: 'Think about detecting something unusual before a human analyst even wakes up.',
  },
  {
    question: 'Which of the following is the single most effective step an individual can take to protect their online accounts?',
    options: [
      'Use the same strong password across all accounts so you only need to remember one',
      'Enable two-factor authentication (2FA) on your most important accounts, so a stolen password alone is not enough to access them',
      'Never use public Wi-Fi under any circumstances, even with a VPN',
      'Change all your passwords on the first day of every month to prevent long-term compromise',
    ],
    correctIndex: 1,
    explanation:
      "Two-factor authentication (2FA) requires a second proof of identity — usually a code sent to your phone or generated by an app — in addition to your password. Even if a criminal steals your password through a phishing attack or a data breach, they cannot access your account without the second factor. For most people, enabling 2FA on email, banking, and social media accounts provides the biggest single improvement in security. Password managers solve the same-password-everywhere problem by generating and storing unique, strong passwords for every site.",
    hint: 'Which option protects you even after your password has been stolen?',
  },
]

export function AIAndCybercrime() {
  useMarkVisited('ai-and-cybercrime')

  return (
    <div className="min-h-screen bg-gradient-to-b from-red-50 to-white dark:from-gray-900 dark:to-gray-950 px-4 py-10 flex flex-col items-center">
      <div className="max-w-2xl w-full space-y-8">

        <div className="text-center space-y-4">
          <div className="text-6xl">&#x1F4BB;</div>
          <h1 className="text-4xl font-bold text-gray-800 dark:text-gray-100 leading-tight">
            AI and cybercrime
          </h1>
          <p className="text-xl text-gray-600 dark:text-gray-300 leading-relaxed">
            How criminals use AI to run cyberattacks — and what you can do to
            protect yourself online.
          </p>
          <div className="flex flex-wrap justify-center gap-2">
            <div className="inline-flex items-center gap-2 bg-blue-100 dark:bg-blue-900 text-blue-700 dark:text-blue-300 text-sm px-4 py-2 rounded-full">
              <span>About 7 min read</span>
            </div>
            <DifficultyBadge level="Intermediate" />
          </div>
          <CompletedBadge lessonId="ai-and-cybercrime" />
          <ShareButton lessonTitle={LESSON_TITLE} />
        </div>

        <KeyTakeaways points={KEY_TAKEAWAYS} />

        <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-sm border border-red-100 dark:border-red-900 p-6 space-y-4">
          <h2 className="text-2xl font-bold text-gray-800 dark:text-gray-100">Why AI has changed the threat landscape</h2>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            Cybercrime is not new — but AI has shifted the balance significantly in favour of attackers.
            Tasks that once required skilled programmers and hours of effort can now be done by anyone
            with access to the right tools, in minutes, at massive scale.
          </p>
          <div className="bg-red-50 dark:bg-red-950 rounded-xl p-4 space-y-2">
            <p className="font-semibold text-red-800 dark:text-red-200 text-sm">What AI gives cybercriminals</p>
            <ul className="text-red-700 dark:text-red-300 text-sm leading-relaxed space-y-1 list-disc list-inside">
              <li>Perfect, personalised phishing messages — no more obvious spelling errors</li>
              <li>Voice and video cloning to impersonate trusted people</li>
              <li>Automated vulnerability scanning — finding weaknesses faster than defenders can patch them</li>
              <li>Ransomware as a service — sophisticated attack tools available to non-technical criminals</li>
              <li>Scale — thousands of targeted attacks simultaneously, at near-zero cost per attempt</li>
            </ul>
          </div>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            The UK's National Cyber Security Centre (NCSC) has reported that AI is already
            being used to enhance the volume and impact of cyberattacks, and that this trend is
            expected to accelerate over the coming years.
          </p>
        </div>

        <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-sm border border-orange-100 dark:border-orange-900 p-6 space-y-4">
          <h2 className="text-2xl font-bold text-gray-800 dark:text-gray-100">AI-powered phishing — the new normal</h2>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            Phishing — tricking you into handing over your password or clicking a malicious link —
            has always been the most common form of cybercrime. AI has made it dramatically more effective.
          </p>
          <div className="space-y-3">
            {[
              {
                icon: '&#x1F4E7;',
                label: 'Personalised at scale',
                text: "AI can scrape your LinkedIn profile, your social media posts, and public company data to generate an email that references your actual employer, your manager's name, and a realistic-sounding scenario — automatically, for thousands of targets simultaneously.",
                color: 'orange',
              },
              {
                icon: '&#x1F3AF;',
                label: 'Spear phishing and whaling',
                text: 'Spear phishing targets a specific individual; whaling targets senior executives. AI makes these highly tailored attacks cheap to produce. A finance director might receive an email that appears to be from the CEO, uses their correct name and title, and references a real current project.',
                color: 'orange',
              },
              {
                icon: '&#x1F4F2;',
                label: 'SMS and voice phishing',
                text: "AI-generated SMS messages (smishing) and phone calls (vishing) are increasingly common. Voice cloning tools can replicate your bank's automated voice system — or even the voice of a family member claiming to be in trouble.",
                color: 'orange',
              },
            ].map(({ icon, label, text, color }) => (
              <div key={label} className={`flex gap-3 items-start bg-${color}-50 dark:bg-${color}-950 rounded-xl p-3`}>
                <span className="text-xl flex-shrink-0 mt-0.5" dangerouslySetInnerHTML={{ __html: icon }} />
                <div>
                  <p className={`font-semibold text-${color}-800 dark:text-${color}-200 text-sm mb-0.5`}>{label}</p>
                  <p className={`text-${color}-700 dark:text-${color}-300 text-sm leading-relaxed`}>{text}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-sm border border-purple-100 dark:border-purple-900 p-6 space-y-4">
          <h2 className="text-2xl font-bold text-gray-800 dark:text-gray-100">Deepfakes — seeing is no longer believing</h2>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            Deepfake technology uses AI to create convincing fake audio and video. In the context
            of cybercrime, this has opened up entirely new forms of fraud.
          </p>
          <div className="space-y-2">
            {[
              "Voice cloning can recreate someone's voice from a few seconds of audio — a voicemail, a YouTube video, or a social media clip. Criminals have used cloned voices to impersonate CEOs and instruct employees to make urgent bank transfers.",
              'In 2024, a Hong Kong company lost $25 million after employees joined what appeared to be a video call with their CFO — who turned out to be a deepfake generated entirely by AI.',
              'Deepfake technology is also used to create false evidence — fabricated videos of public figures saying things they never said — which can be used for blackmail, reputation damage, or political manipulation.',
              "The grandparent scam has been updated with AI: criminals clone the voice of a grandchild and call elderly relatives claiming to be in an emergency, needing money immediately.",
              'Detecting deepfakes is an active research area — tools exist but are far from perfect. The most reliable defence remains verification: call the person back on a known number before acting on any urgent request.',
            ].map((item) => (
              <div key={item} className="flex gap-2 items-start">
                <span className="text-purple-600 dark:text-purple-400 font-bold mt-0.5 flex-shrink-0">&#x2713;</span>
                <p className="text-gray-600 dark:text-gray-300 text-sm leading-relaxed">{item}</p>
              </div>
            ))}
          </div>
        </div>

        <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-sm border border-yellow-100 dark:border-yellow-900 p-6 space-y-4">
          <h2 className="text-2xl font-bold text-gray-800 dark:text-gray-100">Ransomware — a growing industry</h2>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            Ransomware encrypts your files and demands payment — usually in cryptocurrency — for the
            decryption key. Once a tool used only by sophisticated hackers, AI has made it accessible
            as a commercial product.
          </p>
          <div className="space-y-3">
            {[
              {
                icon: '&#x1F512;',
                label: 'How it works',
                text: 'Ransomware typically enters a system through a phishing email, an unpatched software vulnerability, or stolen credentials. Once inside, it silently spreads across the network, identifies the most critical files, then encrypts everything simultaneously — maximising the damage and increasing the chance of payment.',
                color: 'yellow',
              },
              {
                icon: '&#x1F4B0;',
                label: 'Ransomware as a service',
                text: 'Criminal groups now sell ransomware as a subscription product — a non-technical criminal pays a fee, receives the tools and instructions, runs the attack, and splits the ransom payment with the developer. This RaaS model has dramatically expanded the number of people capable of running sophisticated attacks.',
                color: 'yellow',
              },
              {
                icon: '&#x1F3E5;',
                label: 'High-value targets',
                text: 'Hospitals, schools, councils, and critical infrastructure are frequent targets — not because criminals specifically dislike them, but because they are more likely to pay quickly. NHS trusts have faced repeated attacks that have delayed patient care and exposed sensitive data.',
                color: 'yellow',
              },
            ].map(({ icon, label, text, color }) => (
              <div key={label} className={`flex gap-3 items-start bg-${color}-50 dark:bg-${color}-950 rounded-xl p-3`}>
                <span className="text-xl flex-shrink-0 mt-0.5" dangerouslySetInnerHTML={{ __html: icon }} />
                <div>
                  <p className={`font-semibold text-${color}-800 dark:text-${color}-200 text-sm mb-0.5`}>{label}</p>
                  <p className={`text-${color}-700 dark:text-${color}-300 text-sm leading-relaxed`}>{text}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-sm border border-blue-100 dark:border-blue-900 p-6 space-y-4">
          <h2 className="text-2xl font-bold text-gray-800 dark:text-gray-100">AI defences — fighting fire with fire</h2>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            The same AI capabilities that power attacks are also being deployed in defence.
            Modern cybersecurity increasingly relies on AI to keep pace with AI-powered threats.
          </p>
          <div className="space-y-2">
            {[
              'Behavioural AI — tools like Darktrace and Microsoft Defender learn what normal looks like for a user or device: typical login times, usual countries, normal file access patterns. Anything that deviates triggers an alert or automatic block.',
              'Email filtering — AI analyses email content, sender reputation, link destinations, and writing style to identify phishing with far greater accuracy than keyword-based rules alone.',
              'Vulnerability management — AI scans systems for weaknesses and prioritises which patches to apply first based on real-world exploitation risk, helping organisations focus limited security resources.',
              'Automated incident response — when a threat is detected, AI can isolate the affected device, revoke access credentials, and alert the security team in milliseconds — far faster than a human could respond.',
              'Threat intelligence — AI processes millions of data points from across the internet to identify new attack patterns and share them with defenders globally before they spread widely.',
            ].map((item) => (
              <div key={item} className="flex gap-2 items-start">
                <span className="text-blue-600 dark:text-blue-400 font-bold mt-0.5 flex-shrink-0">&#x2713;</span>
                <p className="text-gray-600 dark:text-gray-300 text-sm leading-relaxed">{item}</p>
              </div>
            ))}
          </div>
        </div>

        <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-sm border border-green-100 dark:border-green-900 p-6 space-y-4">
          <h2 className="text-2xl font-bold text-gray-800 dark:text-gray-100">How to protect yourself — practical steps</h2>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            You do not need to be a security expert to protect yourself online. A few
            well-established habits significantly reduce your risk.
          </p>
          <div className="space-y-3">
            {[
              {
                icon: '&#x1F510;',
                label: 'Enable two-factor authentication (2FA)',
                text: 'This is the single most impactful step. Even if a criminal steals your password, they cannot log in without the second factor — usually a code sent to your phone. Enable it on email, banking, and social media first.',
                color: 'green',
              },
              {
                icon: '&#x1F511;',
                label: 'Use a password manager',
                text: 'Tools like Bitwarden, 1Password, or the password manager built into your browser generate and store unique, strong passwords for every site. You never reuse a password, so one breach does not compromise everything.',
                color: 'green',
              },
              {
                icon: '&#x1F504;',
                label: 'Keep software updated',
                text: 'Most ransomware and many other attacks exploit known vulnerabilities in outdated software. Enabling automatic updates for your operating system, browser, and apps is one of the most effective defences available.',
                color: 'green',
              },
              {
                icon: '&#x23F8;&#xFE0F;',
                label: 'Pause before clicking',
                text: 'Urgency is the most common manipulation tactic. Any message — email, text, phone call — that pressures you to act immediately is a red flag. Stop, think, and verify independently before clicking a link or transferring money.',
                color: 'green',
              },
            ].map(({ icon, label, text, color }) => (
              <div key={label} className={`flex gap-3 items-start bg-${color}-50 dark:bg-${color}-950 rounded-xl p-3`}>
                <span className="text-xl flex-shrink-0 mt-0.5" dangerouslySetInnerHTML={{ __html: icon }} />
                <div>
                  <p className={`font-semibold text-${color}-800 dark:text-${color}-200 text-sm mb-0.5`}>{label}</p>
                  <p className={`text-${color}-700 dark:text-${color}-300 text-sm leading-relaxed`}>{text}</p>
                </div>
              </div>
            ))}
          </div>
          <div className="bg-green-50 dark:bg-green-950 rounded-xl p-4">
            <p className="text-green-700 dark:text-green-300 text-sm leading-relaxed">
              <span className="font-semibold">Report it:</span> If you receive a suspicious email in the UK, forward it to report@phishing.gov.uk.
              If you have been scammed, report it to Action Fraud at actionfraud.police.uk or call 0300 123 2040.
              Reporting helps authorities track trends and take down criminal infrastructure.
            </p>
          </div>
        </div>

        <LessonNote lessonId="ai-and-cybercrime" />
        <ReviewLaterButton lessonId="ai-and-cybercrime" />

        <Quiz lessonId="ai-and-cybercrime" questions={quizQuestions} />

        <LessonRating lessonId="ai-and-cybercrime" />
        <LessonFeedback lessonId="ai-and-cybercrime" />

        <RelatedLessons currentId="ai-and-cybercrime" />

        <NextLesson currentId="ai-and-cybercrime" />

      </div>
    </div>
  )
}
