import { Quiz } from '../components/Quiz'
import type { QuizQuestion } from '../components/Quiz'
import { useMarkVisited } from '../hooks/useMarkVisited'
import { NextLesson } from '../components/NextLesson'
import { LessonNote } from '../components/LessonNote'
import { CompletedBadge } from '../components/CompletedBadge'
import { RelatedLessons } from '../components/RelatedLessons'
import { LessonRating } from '../components/LessonRating'
import { LessonFeedback } from '../components/LessonFeedback'
import { ReviewLaterButton } from '../components/ReviewLaterButton'
import { ShareButton } from '../components/ShareButton'
import { KeyTakeaways } from '../components/KeyTakeaways'
import { LessonSeriesBadge } from '../components/LessonSeriesBadge'

const LESSON_TITLE = 'AI and fraud and identity theft'

const KEY_TAKEAWAYS = [
  'Synthetic identity fraud uses AI to combine real and invented information to create entirely new fake identities — making it very difficult for banks and lenders to detect.',
  'Credential stuffing attacks use AI to automatically try millions of stolen username and password combinations across many websites, which is why reusing passwords is so dangerous.',
  'AI can generate fake passports, payslips, and utility bills that look convincing — but organisations are developing AI-powered countermeasures to detect them.',
  'You can protect yourself by registering with CIFAS, freezing your credit, checking Have I Been Pwned, and using a password manager with unique passwords for every account.',
  'If your identity is stolen, report it to Action Fraud and your bank immediately, place a CIFAS protective registration, and know that emotional support is available — identity theft is distressing and you are not alone.',
]

const quizQuestions: QuizQuestion[] = [
  {
    question: 'What is synthetic identity fraud, and what role does AI play in it?',
    options: [
      'Fraudsters steal a real person\'s entire identity — name, address, National Insurance number — and use it to open credit accounts in that person\'s name',
      'Fraudsters use AI to combine a real National Insurance number with invented names, addresses, and dates of birth to create a new fake identity that does not belong to any single real person',
      'Fraudsters use deepfake video technology to impersonate real people in video calls with bank employees, convincing them to transfer money to fraudulent accounts',
      'Fraudsters hack into government databases using AI tools to steal real identity documents and then sell them on the dark web to criminals in other countries',
    ],
    correctIndex: 1,
    explanation:
      'Synthetic identity fraud involves combining genuine information (often a real National Insurance number, which might belong to a child or someone who rarely uses credit) with invented details — a fake name, a different address, a false date of birth. The resulting identity does not belong to a real person, so victims often do not notice for years. AI accelerates this by generating convincing fake personas at scale, making it one of the fastest-growing types of financial fraud.',
    hint: 'Think about what makes it hard for banks to detect — the victim does not even know they are a victim.',
  },
  {
    question: 'What is credential stuffing and why does reusing passwords make you vulnerable to it?',
    options: [
      'Credential stuffing is when fraudsters guess your password by trying common words and phrases — reusing passwords does not affect your vulnerability to this attack',
      'Credential stuffing is when AI automatically tries millions of username and password combinations stolen from data breaches across many different websites — if you reuse a password, one breach can unlock all your accounts',
      'Credential stuffing is when hackers stuff malicious code into login forms to bypass security checks — using the same password makes it easier for the code to be inserted',
      'Credential stuffing is a form of phishing where fraudsters send emails pretending to be websites you use — reusing passwords means more accounts are at risk if you click a fake link',
    ],
    correctIndex: 1,
    explanation:
      'When a website is hacked, the stolen usernames and passwords are often sold on the dark web. Fraudsters then use AI-powered tools to automatically try those stolen credentials across hundreds of other websites — banks, email providers, shopping sites. If you use the same password on multiple sites, one breach can unlock everything. This is why security experts recommend using a different password for every website, ideally generated by a password manager.',
    hint: 'Think about what happens when a large database of usernames and passwords gets stolen and sold.',
  },
  {
    question: 'How are fraudsters using AI to create fake documents, and how are organisations fighting back?',
    options: [
      'AI is used to print physical documents using 3D printers — organisations fight back by using ultraviolet light scanners to detect printer ink',
      'AI image generation tools can create convincing fake passports, payslips, and utility bills — organisations are deploying AI-powered document verification tools that analyse micro-details, fonts, and metadata to detect fakes',
      'AI is used to intercept real documents in the post and alter them digitally — organisations fight back by switching entirely to digital-only documentation that cannot be physically intercepted',
      'AI tools automatically order genuine documents from government agencies using stolen personal data — organisations fight back by adding extra security questions to document applications',
    ],
    correctIndex: 1,
    explanation:
      'AI image generation tools have made it much easier to create fake documents that look convincing to the human eye — fake payslips for mortgage applications, fake utility bills for identity verification, fake passports for account opening. In response, organisations like banks and letting agents are using AI-powered verification tools (such as those from Onfido or Jumio) that analyse hundreds of micro-details in document images — font spacing, security features, metadata — to detect forgeries that humans would miss.',
    hint: 'Think about how the same AI technology that creates fakes can also be used to detect them.',
  },
  {
    question: 'What is a CIFAS protective registration and when would you use it?',
    options: [
      'It is a government compensation scheme that pays you back if you lose money to identity fraud — you register after a fraud has occurred to claim your refund',
      'It is a flag placed on your credit file that alerts lenders to carry out extra identity checks before approving any credit applications in your name — useful if you think your personal information has been stolen',
      'It is a legal injunction that prevents any new credit accounts being opened in your name permanently — used when your identity has already been stolen and you want to stop all future applications',
      'It is a service run by the police that monitors the dark web for your personal details and alerts you by text message if they appear in any stolen data sets',
    ],
    correctIndex: 1,
    explanation:
      'A CIFAS protective registration (costing around £25 for two years) adds a flag to your credit file. When a lender sees this flag, they know to carry out extra checks before approving any credit application — like calling you to confirm you really did apply. This makes it much harder for a fraudster to use your details to open accounts, even if they already have your name, address, and date of birth. It is particularly useful if you know your data has been stolen in a breach.',
    hint: 'Think about what you would want lenders to do before approving any application made in your name.',
  },
  {
    question: 'If you discovered your identity had been stolen, what should you do first?',
    options: [
      'Change all your passwords immediately and wait to see if any fraudulent accounts appear on your credit report before contacting anyone else',
      'Post about it on social media so your friends and family know to be vigilant if anyone contacts them pretending to be you',
      'Report it to Action Fraud (actionfraud.police.uk or 0300 123 2040) and contact your bank immediately, then place a CIFAS protective registration and check your credit report',
      'Contact the company whose data breach caused the theft and demand they compensate you before taking any other steps',
    ],
    correctIndex: 2,
    explanation:
      'If you discover your identity has been stolen, act quickly. Report it to Action Fraud — the UK\'s national fraud reporting centre — and call your bank to alert them and freeze or monitor your accounts. Then place a CIFAS protective registration to flag future credit applications. Check your credit report (Experian, Equifax, or TransUnion offer free reports) for any accounts you did not open. Remember that identity theft is distressing and Victim Support and Citizens Advice can provide emotional support and practical guidance.',
    hint: 'Think about who the official bodies are that deal with fraud in the UK.',
  },
]

export function AIAndFraudAndIdentityTheft() {
  useMarkVisited('ai-and-fraud-and-identity-theft')

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-red-50 dark:from-gray-900 dark:to-gray-800">
      <div className="max-w-3xl mx-auto px-4 py-10">
        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center gap-3 mb-4">
            <span className="text-4xl">🔐</span>
            <div>
              <p className="text-sm font-medium text-red-600 dark:text-red-400 uppercase tracking-wide">AI in the real world</p>
              <h1 className="text-3xl font-bold text-gray-900 dark:text-white">{LESSON_TITLE}</h1>
            </div>
          </div>
          <p className="text-gray-600 dark:text-gray-300 text-lg">
            AI has made identity fraud faster, cheaper, and harder to detect — but it has also given us better tools to fight back.
            Here is what you need to know to protect yourself.
          </p>
          <div className="flex flex-wrap gap-3 mt-4">
            <CompletedBadge lessonId="ai-and-fraud-and-identity-theft" />
            <ReviewLaterButton lessonId="ai-and-fraud-and-identity-theft" />
            <ShareButton lessonTitle={LESSON_TITLE} />
          </div>
        </div>

        <KeyTakeaways points={KEY_TAKEAWAYS} />

        <LessonSeriesBadge lessonId="ai-and-fraud-and-identity-theft" />

        {/* Content */}
        <div className="prose prose-gray dark:prose-invert max-w-none mb-10 space-y-6">

          <section>
            <h2 className="text-2xl font-semibold text-gray-800 dark:text-white mt-8 mb-3">Synthetic identity fraud — creating people who do not exist</h2>
            <p className="text-gray-700 dark:text-gray-300">
              Traditional identity theft involves stealing a real person&apos;s identity wholesale — their name, address, and National Insurance number
              — and using it to open accounts. But AI has enabled a more sophisticated and harder-to-detect version: <strong>synthetic identity fraud</strong>.
            </p>
            <p className="text-gray-700 dark:text-gray-300">
              In synthetic identity fraud, criminals combine a real National Insurance number (often stolen from a child, whose credit history is
              blank and who will not notice for years) with a completely invented name, address, and date of birth. The result is a fake person who does
              not actually exist — but whose identity passes basic identity checks because the NI number is genuine.
            </p>
            <p className="text-gray-700 dark:text-gray-300">
              AI accelerates this at scale. Tools can generate thousands of convincing fake identities, complete with plausible names, addresses,
              and supporting details. These synthetic identities are then used to apply for credit cards, loans, and bank accounts. Fraudsters
              patiently build up a credit history over months or years, then &quot;bust out&quot; — maxing out every available credit line and
              disappearing overnight.
            </p>
            <p className="text-gray-700 dark:text-gray-300">
              Because the victim is a fictional person, no one realises they have been defrauded until the lender tries to chase the debt. UK
              Finance estimates synthetic identity fraud costs British lenders hundreds of millions of pounds per year.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-800 dark:text-white mt-8 mb-3">Account takeover — when AI tries to log in as you</h2>
            <p className="text-gray-700 dark:text-gray-300">
              Most of us reuse passwords. It is understandable — remembering dozens of different passwords for every website you use is genuinely
              difficult. But this habit has created a massive vulnerability that criminals exploit using AI.
            </p>
            <p className="text-gray-700 dark:text-gray-300">
              When a website is hacked, the stolen usernames and passwords are usually sold on the dark web. Fraudsters then use automated tools —
              powered by AI — to try those credentials across hundreds of other websites simultaneously. This is called <strong>credential stuffing</strong>.
              The AI can attempt millions of logins per hour, far faster than any human could manage.
            </p>
            <p className="text-gray-700 dark:text-gray-300">
              If you used the same email and password for a small online shop that was hacked as you did for your bank, email account, or Amazon,
              the attacker has now potentially accessed everything. This is not theoretical — credential stuffing attacks compromise millions
              of accounts every year.
            </p>
            <p className="text-gray-700 dark:text-gray-300">
              The solution is straightforward even if it takes a little effort: use a different password for every website. A password manager
              (like Bitwarden, which is free and open source, or 1Password) generates and stores unique passwords so you do not need to remember them.
              Combined with two-factor authentication — where a login also requires a code sent to your phone — this dramatically reduces your
              vulnerability.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-800 dark:text-white mt-8 mb-3">AI-generated fake documents — and how they are detected</h2>
            <p className="text-gray-700 dark:text-gray-300">
              Opening a bank account, applying for a mortgage, or renting a property all require proof of identity — a passport, driving licence,
              payslip, or utility bill. Fraudsters have always forged documents, but AI image generation tools have made convincing fakes dramatically
              easier to produce.
            </p>
            <p className="text-gray-700 dark:text-gray-300">
              A realistic-looking fake payslip for a mortgage application, a convincing utility bill for an address verification — these can now be
              generated in minutes using widely available AI tools. For a human reviewer glancing at a document, many of these fakes are
              indistinguishable from the real thing.
            </p>
            <p className="text-gray-700 dark:text-gray-300">
              In response, organisations are deploying <strong>AI-powered document verification</strong>. Tools from companies like Onfido, Jumio,
              and Mitek analyse hundreds of micro-details that humans would never notice: the exact spacing of fonts on a passport, the precise
              placement of security features, the metadata embedded in an image file, inconsistencies in shadows or lighting that suggest digital
              manipulation.
            </p>
            <p className="text-gray-700 dark:text-gray-300">
              This is an ongoing arms race: as AI-generated fakes improve, detection tools improve to match. For now, the AI detectors have a
              meaningful edge — but the field moves quickly.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-800 dark:text-white mt-8 mb-3">Protecting your digital identity — practical steps</h2>
            <p className="text-gray-700 dark:text-gray-300">
              The good news is that there are concrete, practical steps you can take to significantly reduce your risk:
            </p>
            <ul className="list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300">
              <li>
                <strong>Use Have I Been Pwned</strong> (haveibeenpwned.com) — enter your email address to see if it has appeared in any known
                data breaches. If it has, change the passwords for those accounts immediately.
              </li>
              <li>
                <strong>Use a password manager</strong> — Bitwarden is free, secure, and works across all your devices. It generates a unique,
                random password for every site and remembers them for you.
              </li>
              <li>
                <strong>Enable two-factor authentication</strong> — especially for your email, banking, and social media accounts. Even if
                a fraudster has your password, they cannot log in without the second factor.
              </li>
              <li>
                <strong>Register with CIFAS</strong> — for around £25 for two years, a CIFAS protective registration adds a flag to your credit
                file so that lenders carry out extra checks before approving any application in your name.
              </li>
              <li>
                <strong>Check your credit report regularly</strong> — Experian, Equifax, and TransUnion all offer free credit reports. Look for
                any accounts you did not open. You can also place a temporary credit freeze if you are concerned.
              </li>
              <li>
                <strong>Submit a Subject Access Request (SAR/DSAR)</strong> — any organisation that holds your personal data must give it to
                you on request. If you suspect a company has shared your data incorrectly, you can ask for a full record of what they hold.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-800 dark:text-white mt-8 mb-3">What to do if your identity is stolen</h2>
            <p className="text-gray-700 dark:text-gray-300">
              Discovering that your identity has been stolen is frightening and distressing. Here is what to do, step by step:
            </p>
            <ol className="list-decimal list-inside space-y-2 text-gray-700 dark:text-gray-300">
              <li>
                <strong>Report to Action Fraud</strong> — visit actionfraud.police.uk or call 0300 123 2040. This is the UK&apos;s national
                fraud reporting centre. Keep your reference number.
              </li>
              <li>
                <strong>Contact your bank immediately</strong> — alert them to the fraud and ask them to freeze or monitor your accounts.
                They have dedicated fraud teams and are required to help you.
              </li>
              <li>
                <strong>Place a CIFAS protective registration</strong> — this will make it harder for the fraudster to open further accounts
                in your name while you deal with the situation.
              </li>
              <li>
                <strong>Check and dispute your credit report</strong> — contact each of the three credit reference agencies (Experian, Equifax,
                and TransUnion) to flag any fraudulent entries and ask for them to be investigated and removed.
              </li>
              <li>
                <strong>Get support</strong> — identity theft is distressing, and you are not alone. Victim Support (victimsupport.org.uk)
                and Citizens Advice (citizensadvice.org.uk) can provide both emotional support and practical guidance on your next steps.
              </li>
            </ol>
            <p className="text-gray-700 dark:text-gray-300">
              Remember: you are not at fault. Sophisticated fraud can happen to anyone, and the systems exist to help you recover.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-800 dark:text-white mt-8 mb-3">The bottom line</h2>
            <p className="text-gray-700 dark:text-gray-300">
              AI has made identity fraud faster, more scalable, and harder to detect. Fraudsters can generate thousands of fake identities,
              test millions of stolen passwords, and create convincing fake documents — all with minimal human effort. But the same technology
              is being used defensively: AI-powered fraud detection, document verification, and anomaly detection systems are getting better
              all the time.
            </p>
            <p className="text-gray-700 dark:text-gray-300">
              The most powerful thing you can do is take a few simple precautions now — unique passwords, two-factor authentication, regular
              credit checks — rather than wait until something goes wrong. A little effort today can prevent a great deal of stress tomorrow.
            </p>
          </section>
        </div>

        <LessonNote lessonId="ai-and-fraud-and-identity-theft" />

        <Quiz lessonId="ai-and-fraud-and-identity-theft" questions={quizQuestions} lessonTitle={LESSON_TITLE} />

        <LessonRating lessonId="ai-and-fraud-and-identity-theft" />
        <LessonFeedback lessonId="ai-and-fraud-and-identity-theft" />

        <RelatedLessons currentId="ai-and-fraud-and-identity-theft" />

        <NextLesson currentId="ai-and-fraud-and-identity-theft" />
      </div>
    </div>
  )
}
