import { Quiz } from '../components/Quiz'
import type { QuizQuestion } from '../components/Quiz'
import { useMarkVisited } from '../hooks/useMarkVisited'
import { NextLesson } from '../components/NextLesson'
import { LessonNote } from '../components/LessonNote'
import { CompletedBadge } from '../components/CompletedBadge'
import { RelatedLessons } from '../components/RelatedLessons'
import { LessonRating } from '../components/LessonRating'
import { LessonFeedback } from '../components/LessonFeedback'
import { ReviewLaterButton } from '../components/ReviewLaterButton'
import { ShareButton } from '../components/ShareButton'

const LESSON_TITLE = 'AI and the law'

const quizQuestions: QuizQuestion[] = [
  {
    question: 'How is AI currently being used in the legal profession?',
    options: [
      'AI has fully replaced human lawyers in UK courts since 2023',
      'AI is used for tasks like searching case law, reviewing contracts, and summarising documents — but final legal judgements still require human lawyers and judges',
      'AI is used only for billing and administrative tasks, never for legal analysis',
      'AI is banned from all legal work in the UK and EU',
    ],
    correctIndex: 1,
    explanation:
      'AI tools are increasingly common in legal work — large law firms use them to search decades of case law in seconds, check contracts for missing clauses, and summarise lengthy documents. However, AI does not make legal decisions. Lawyers and judges are still responsible for interpreting the law, weighing evidence, and reaching conclusions. AI is a research assistant, not a replacement.',
    hint: 'Think about what AI is good at (fast searching and summarising) versus what still requires human judgement.',
  },
  {
    question: 'What concern do courts have about AI-generated evidence, such as audio or video?',
    options: [
      'AI-generated evidence is always accepted because it is produced by a computer',
      'Courts worry that deepfakes — convincingly realistic AI-generated audio or video — could be used to fabricate evidence that is very hard to detect as fake',
      'Courts only reject AI evidence because it cannot be printed on paper',
      'AI evidence is banned in UK courts but freely used in US courts',
    ],
    correctIndex: 1,
    explanation:
      "Deepfakes — AI-generated images, audio, and video that look or sound real — pose a serious challenge to court evidence. If someone can produce a convincing fake recording of a person saying something they never said, how can courts assess its authenticity? This is an active area of legal debate, and some jurisdictions are introducing laws specifically about AI-generated evidence.",
    hint: "The key word is 'deepfakes' — content that looks or sounds real but was generated by AI.",
  },
  {
    question: 'What does the EU AI Act (2024) classify as high-risk AI?',
    options: [
      'Any AI that can answer questions or hold a conversation',
      'Only AI used in military weapons',
      'AI systems used in areas like employment decisions, credit scoring, healthcare, and the justice system — where errors can seriously harm people',
      'Any AI that costs more than €10,000 to build',
    ],
    correctIndex: 2,
    explanation:
      "The EU AI Act categorises AI by risk level. 'High-risk' AI includes systems that affect employment (hiring, performance assessment), access to credit and financial services, healthcare, education, and law enforcement. These systems face the strictest requirements: they must be transparent, accurate, and subject to human oversight. The idea is that where AI decisions have the biggest impact on people's lives, the safeguards must be strongest.",
    hint: "Think about the areas of life where an AI getting it wrong would have the most serious consequences for an individual.",
  },
  {
    question: "Under UK GDPR Article 22, what right do you have when a company makes an automated decision about you?",
    options: [
      'The right to sue the AI system itself in a UK court',
      "The right not to be subject to a decision based solely on automated processing that significantly affects you — and the right to request a human review",
      'The right to see the AI company\'s source code',
      'The right to have the decision reversed automatically if you complain',
    ],
    correctIndex: 1,
    explanation:
      "Article 22 of the UK GDPR (General Data Protection Regulation) gives you the right to not be subjected to a decision made entirely by automated means — such as an algorithm — if that decision significantly affects you (e.g. a loan refusal, job rejection, or insurance quote). You can request that a human being reviews the decision. The company must tell you the decision was automated and explain how you can challenge it.",
    hint: "UK GDPR gives you data rights — one of them specifically covers automated decisions that affect you significantly.",
  },
  {
    question: 'If an AI system gives you wrong legal advice that causes you financial harm, who is legally responsible in the UK?',
    options: [
      'The AI itself, which can be taken to court',
      'No one — AI tools are not covered by any existing law',
      'The company that provided the AI tool, because businesses remain responsible for services they offer regardless of whether a human or AI delivered them',
      'The government, which must compensate users for all AI errors',
    ],
    correctIndex: 2,
    explanation:
      "UK law does not recognise AI as a legal person, so the AI itself cannot be sued. Responsibility falls on the company that deployed the tool. Under consumer protection law and the Consumer Rights Act 2015, a business is responsible for the services it provides. If an AI legal tool gave you bad advice and you suffered harm as a result, your claim would be against the company, not the AI.",
    hint: "Legal responsibility always sits with a human or a company — AI has no legal personality.",
  },
]

export function AIAndTheLaw() {
  useMarkVisited('ai-and-the-law')

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-50 to-white px-4 py-10 flex flex-col items-center">
      <div className="max-w-2xl w-full space-y-8">

        <div className="text-center space-y-4">
          <div className="text-6xl">&#x2696;&#xFE0F;</div>
          <h1 className="text-4xl font-bold text-gray-800 leading-tight">
            AI and the law
          </h1>
          <p className="text-xl text-gray-600 leading-relaxed">
            How AI is changing legal work, what AI regulation means for ordinary people,
            and how to challenge an AI decision that affects your life.
          </p>
          <div className="flex flex-wrap justify-center gap-2">
            <div className="inline-flex items-center gap-2 bg-blue-100 text-blue-700 text-sm px-4 py-2 rounded-full">
              <span>About 6 min read</span>
            </div>
            <div className="inline-flex items-center gap-2 bg-amber-100 text-amber-700 text-sm px-4 py-2 rounded-full font-semibold">
              <span>Intermediate</span>
            </div>
          </div>
          <CompletedBadge lessonId="ai-and-the-law" />
          <ShareButton lessonTitle={LESSON_TITLE} />
        </div>

        <div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-6 space-y-4">
          <h2 className="text-2xl font-bold text-gray-800">AI in the legal profession</h2>
          <p className="text-gray-600 leading-relaxed">
            Law has always been paper-heavy. Contracts run to hundreds of pages. Court cases produce thousands
            of documents. A junior solicitor might spend weeks searching precedents that an AI can find in seconds.
            This is where AI is already transforming legal work.
          </p>
          <div className="space-y-3">
            {[
              {
                icon: '&#x1F4C4;',
                label: 'Contract review',
                text: 'AI tools scan contracts for unusual clauses, missing terms, or potential risks. Tools like Harvey AI and Luminance are used by major law firms to check thousands of pages of agreements in minutes.',
              },
              {
                icon: '&#x1F50E;',
                label: 'Legal research',
                text: 'Finding relevant case law — previous court rulings that set legal precedent — used to take days. AI tools search millions of cases instantly, helping lawyers build arguments faster.',
              },
              {
                icon: '&#x1F4DD;',
                label: 'Document summarisation',
                text: 'In complex litigation, AI reads and summarises lengthy witness statements, expert reports, and evidence files, highlighting what the legal team needs to focus on.',
              },
              {
                icon: '&#x26A0;&#xFE0F;',
                label: 'Important limits',
                text: "AI does not make legal decisions. It assists lawyers, but a human being is always responsible for the legal advice given. Solicitors and barristers remain professionally and legally accountable — they cannot blame the AI if the advice is wrong.",
              },
            ].map(({ icon, label, text }) => (
              <div key={label} className="flex gap-3 items-start">
                <span className="text-xl flex-shrink-0 mt-0.5" dangerouslySetInnerHTML={{ __html: icon }} />
                <div>
                  <p className="font-semibold text-gray-800 text-sm mb-0.5">{label}</p>
                  <p className="text-gray-600 text-sm leading-relaxed">{text}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="bg-white rounded-2xl shadow-sm border border-red-100 p-6 space-y-4">
          <h2 className="text-2xl font-bold text-gray-800">AI in the courts: deepfakes and evidence</h2>
          <p className="text-gray-600 leading-relaxed">
            The rise of AI-generated content is posing a direct challenge to courts, which depend on the
            authenticity of evidence.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {[
              { icon: '&#x1F3A5;', title: 'Deepfake video', text: "AI can generate realistic video of a person saying or doing something they never did. If this is submitted as evidence, how can a court verify it is real? Courts are developing new authentication processes, but the technology is advancing faster than the rules." },
              { icon: '&#x1F3A4;', title: 'Synthetic audio', text: "Voice cloning tools can mimic a person's voice with a short sample. A fake audio recording of someone making a threat or confession could be very convincing and very harmful if accepted as evidence." },
              { icon: '&#x1F916;', title: 'Prediction tools', text: "Some US courts have used AI 'risk assessment' tools to help judges decide bail or sentencing. These tools are controversial because they have been found to contain racial bias — flagging Black defendants as higher risk more often than white defendants with similar records." },
              { icon: '&#x1F1EC;&#x1F1E7;', title: 'The UK position', text: "UK courts have not adopted AI sentencing tools. The UK Judicial College has issued guidance that judges should be cautious about AI-generated content and consider authentication carefully. No UK legislation specifically governs AI evidence yet." },
            ].map(({ icon, title, text }) => (
              <div key={title} className="bg-red-50 rounded-xl p-4">
                <div className="flex items-center gap-2 mb-2">
                  <span className="text-xl" dangerouslySetInnerHTML={{ __html: icon }} />
                  <p className="font-semibold text-gray-800 text-sm">{title}</p>
                </div>
                <p className="text-gray-600 text-sm leading-relaxed">{text}</p>
              </div>
            ))}
          </div>
        </div>

        <div className="bg-white rounded-2xl shadow-sm border border-blue-100 p-6 space-y-4">
          <h2 className="text-2xl font-bold text-gray-800">The EU AI Act</h2>
          <p className="text-gray-600 leading-relaxed">
            The EU AI Act, which came into force in 2024, is the world&rsquo;s first comprehensive law specifically
            regulating artificial intelligence. It matters even if you are not in the EU &mdash; because many of the
            AI tools you use are built by companies operating in Europe.
          </p>
          <div className="bg-blue-50 rounded-xl p-4 space-y-2">
            <p className="font-semibold text-blue-800 text-sm">The four risk tiers</p>
            <ul className="text-blue-700 text-sm leading-relaxed space-y-1 list-disc list-inside">
              <li><strong>Unacceptable risk (banned):</strong> social credit scoring, real-time remote biometric surveillance in public spaces, AI that manipulates people subliminally</li>
              <li><strong>High risk (strict rules):</strong> AI in hiring, credit, healthcare, education, law enforcement — must be transparent, accurate, and human-overseen</li>
              <li><strong>Limited risk (transparency required):</strong> chatbots must tell you they are AI; deepfakes must be labelled</li>
              <li><strong>Minimal risk (no rules):</strong> spam filters, AI in video games, most recommendation engines</li>
            </ul>
          </div>
          <p className="text-gray-600 leading-relaxed">
            The UK left the EU before the AI Act was finalised. The UK government has chosen a
            &ldquo;pro-innovation&rdquo; approach &mdash; rather than one central AI law, it expects existing
            regulators (the ICO, FCA, CMA) to apply their existing rules to AI in their sectors. Critics say
            this leaves gaps; supporters say it is more flexible.
          </p>
        </div>

        <div className="bg-white rounded-2xl shadow-sm border border-amber-100 p-6 space-y-4">
          <h2 className="text-2xl font-bold text-gray-800">Liability: who is responsible when AI gets it wrong?</h2>
          <p className="text-gray-600 leading-relaxed">
            This is one of the most important &mdash; and unsettled &mdash; questions in AI law.
          </p>
          <div className="space-y-3">
            {[
              {
                icon: '&#x1F3E2;',
                label: 'The company that deployed the AI',
                text: "Under UK consumer protection law, a business is responsible for the services it provides, whether a human or AI delivered them. If an insurance company's AI refuses your claim wrongly, you claim against the insurer — not the AI.",
              },
              {
                icon: '&#x1F6E0;&#xFE0F;',
                label: 'The AI developer',
                text: "In some cases, liability may extend to the company that built the AI. If a product was fundamentally defective — like a medical AI that consistently gave wrong diagnoses — the developer could face claims under product liability law.",
              },
              {
                icon: '&#x1F464;',
                label: 'The user',
                text: "If a professional (like a lawyer or doctor) uses AI and fails to check its output before relying on it, they may bear responsibility. The AI is a tool — the professional using it remains accountable for the advice they give.",
              },
            ].map(({ icon, label, text }) => (
              <div key={label} className="flex gap-3 items-start">
                <span className="text-xl flex-shrink-0 mt-0.5" dangerouslySetInnerHTML={{ __html: icon }} />
                <div>
                  <p className="font-semibold text-gray-800 text-sm mb-0.5">{label}</p>
                  <p className="text-gray-600 text-sm leading-relaxed">{text}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="bg-white rounded-2xl shadow-sm border border-emerald-100 p-6 space-y-4">
          <h2 className="text-2xl font-bold text-gray-800">Your rights: challenging automated decisions</h2>
          <p className="text-gray-600 leading-relaxed">
            If an AI system makes a decision about you &mdash; refusing a loan, rejecting a job application,
            setting an insurance premium &mdash; you have real legal rights in the UK.
          </p>
          <div className="bg-emerald-50 rounded-xl p-4 space-y-2">
            <p className="font-semibold text-emerald-800 text-sm">What you can do</p>
            <ul className="text-emerald-700 text-sm leading-relaxed space-y-2 list-disc list-inside">
              <li><strong>Ask for an explanation:</strong> under UK GDPR, companies must tell you if a significant decision about you was made automatically, and explain the main factors involved</li>
              <li><strong>Request human review:</strong> Article 22 of the UK GDPR gives you the right to ask for a human being to review any significant automated decision</li>
              <li><strong>Make a subject access request:</strong> you can ask what data a company holds about you and how it was used in an automated decision</li>
              <li><strong>Complain to the ICO:</strong> if a company refuses to explain or review an automated decision affecting you, you can report this to the Information Commissioner&rsquo;s Office (ico.org.uk)</li>
              <li><strong>Seek specialist advice:</strong> Citizens Advice, the Financial Ombudsman Service (for financial decisions), and employment tribunals (for hiring decisions) can all help</li>
            </ul>
          </div>
          <div className="bg-gray-50 rounded-xl p-4">
            <p className="text-gray-700 text-sm leading-relaxed">
              <strong>Key point:</strong> AI has no legal personality in the UK. It cannot be sued, prosecuted, or
              held responsible. A human or company is always behind any AI system you interact with, and that is
              who your legal rights apply to.
            </p>
          </div>
        </div>

        <ReviewLaterButton lessonId="ai-and-the-law" />
        <LessonNote lessonId="ai-and-the-law" lessonTitle={LESSON_TITLE} />

        <Quiz questions={quizQuestions} lessonId="ai-and-the-law" lessonTitle={LESSON_TITLE} />

        <LessonFeedback lessonId="ai-and-the-law" />
        <LessonRating lessonId="ai-and-the-law" />
        <RelatedLessons currentId="ai-and-the-law" />
        <NextLesson currentId="ai-and-the-law" />
      </div>
    </div>
  )
}
