import { useState } from 'react'

type Term = {
  id: string
  term: string
  correct: string
  explanation: string
  distractors: [string, string, string]
}

const TERMS: Term[] = [
  {
    id: 'neural-network',
    term: 'Neural network',
    correct: 'A computer system loosely inspired by the human brain, made of layers of connected nodes that learn patterns from data',
    explanation: 'Neural networks are the foundation of modern AI. Each "node" performs a simple calculation, but millions of nodes connected in layers can learn to recognise images, understand speech, and generate text. They are called "neural" because they loosely mimic how neurons in the brain connect, though the comparison is quite rough.',
    distractors: [
      'A physical network of computers physically shaped like a brain, used for parallel AI computations',
      'A type of internet connection optimised for AI data transfers, faster than standard broadband',
    ] as unknown as [string, string, string],
  },
  {
    id: 'training-data',
    term: 'Training data',
    correct: 'The large collection of examples — text, images, numbers — that an AI system learns from before it is deployed',
    explanation: "Training data is what the AI learns from. A spam filter is trained on millions of labelled emails (spam/not spam). An image classifier is trained on millions of labelled photos. The quality and diversity of training data is one of the most important factors in an AI's performance and fairness.",
    distractors: [
      'Data generated by an AI system during its operation, which is used to train a second AI to monitor the first',
      'Exercises and puzzles given to programmers to teach them how to write AI code more efficiently',
    ] as unknown as [string, string, string],
  },
  {
    id: 'hallucination',
    term: 'Hallucination',
    correct: 'When an AI confidently generates false or made-up information — such as a non-existent case, statistic, or event — that sounds plausible but is wrong',
    explanation: "AI hallucination is one of the most important limitations of large language models. Because these models generate text based on patterns rather than true knowledge, they can produce confident-sounding statements that are completely false. Famous examples include ChatGPT inventing legal cases that do not exist and generating fake scientific citations.",
    distractors: [
      'When an AI becomes confused by contradictory inputs and goes into an error state, producing no output',
      'A visual glitch where an AI image generator produces distorted faces or extra fingers in generated images',
    ] as unknown as [string, string, string],
  },
  {
    id: 'llm',
    term: 'Large language model (LLM)',
    correct: 'An AI system trained on vast amounts of text that can generate, summarise, translate, and converse in human language — examples include GPT-4, Claude, and Gemini',
    explanation: "Large language models are trained on hundreds of billions of words from books, websites, and other text sources. They learn patterns in language so thoroughly that they can generate coherent, contextually relevant text, answer questions, write code, and translate between languages. They do not 'know' things the way humans do — they predict the most likely next word based on patterns.",
    distractors: [
      'A physical machine learning processor chip specifically designed to run language translation software at high speed',
      'A formal programming language used by AI researchers to describe and specify the behaviour of AI systems',
    ] as unknown as [string, string, string],
  },
  {
    id: 'bias',
    term: 'Bias (in AI)',
    correct: 'When an AI system produces systematically unfair or inaccurate outputs for certain groups — often because its training data reflected historical inequalities',
    explanation: "AI bias happens when the patterns an AI learns from training data encode real-world discrimination or underrepresentation. For example, an AI hiring tool trained on historical hiring data (where certain groups were underrepresented) may perpetuate that discrimination. Bias is not always visible in the AI's code — it emerges from the data.",
    distractors: [
      'A deliberate feature built into AI systems to ensure they give priority to certain users who pay for premium access',
      'The tendency of AI systems to use too much computing power, making them biased towards expensive hardware',
    ] as unknown as [string, string, string],
  },
  {
    id: 'fine-tuning',
    term: 'Fine-tuning',
    correct: 'Taking a pre-trained AI model and training it further on a smaller, specific dataset to specialise it for a particular task',
    explanation: "Training a large language model from scratch costs millions of pounds. Fine-tuning is a cheaper alternative: take a general model (like GPT-3) that already understands language, then train it on a smaller dataset of, say, medical records to create a medical AI assistant. The model retains its general language ability and gains specific domain knowledge.",
    distractors: [
      'Adjusting the physical hardware that runs an AI system to improve its speed and reduce energy consumption',
      'A type of user feedback where people rate AI responses so engineers can manually improve individual outputs',
    ] as unknown as [string, string, string],
  },
  {
    id: 'token',
    term: 'Token',
    correct: 'The basic unit that large language models process — roughly a word or part of a word. "unbelievable" might be 3 tokens: "un", "believ", "able"',
    explanation: "Language models do not process text character by character or word by word — they process tokens, which are chunks of characters. Common words are one token, rare or long words are split into multiple tokens. The token limit of a model (its 'context window') determines how much text it can process at once. GPT-4 can process around 128,000 tokens — roughly 100,000 words.",
    distractors: [
      'A digital certificate that proves an AI system has been approved for use in regulated industries',
      'A unit of cryptocurrency used to pay AI companies for each API query made to their language models',
    ] as unknown as [string, string, string],
  },
  {
    id: 'inference',
    term: 'Inference',
    correct: "Using a trained AI model to make predictions or generate outputs — as distinct from 'training', which is when the model learns",
    explanation: "Training is the expensive phase where the AI learns from data — this can take months and millions of pounds of computing. Inference is using the trained model — this is what happens every time you type a message to ChatGPT and it responds. Inference is much cheaper than training but still requires significant computing resources at scale.",
    distractors: [
      "A feature in AI systems that allows them to draw logical conclusions from incomplete data using formal deduction rules",
      "The process by which an AI model is tested against new data to check its accuracy before it is allowed to be deployed",
    ] as unknown as [string, string, string],
  },
  {
    id: 'prompt',
    term: 'Prompt',
    correct: 'The input or instruction given to an AI system — the text, question, or command that tells the AI what you want it to do',
    explanation: "A prompt is simply what you say to an AI. 'What is the capital of France?' is a prompt. 'Write a cover letter for a marketing role' is a prompt. 'Prompt engineering' is the skill of crafting prompts that get the best outputs from AI systems — a skill that has become genuinely valuable as AI becomes widely used.",
    distractors: [
      "A warning message displayed by an AI system when it detects that a user is asking it to do something potentially harmful",
      "The technical name for the first training stage of a language model, during which it learns basic grammar rules",
    ] as unknown as [string, string, string],
  },
  {
    id: 'overfitting',
    term: 'Overfitting',
    correct: "When an AI model learns the training data too closely — memorising specific examples rather than learning general patterns — making it perform poorly on new data",
    explanation: "Overfitting is a common problem in machine learning. Imagine training a spam filter on 100 specific spam emails — it memorises every word of those emails. When a new spam email arrives with slightly different wording, it fails to detect it. A well-generalised model learns the pattern (urgent language, suspicious links) rather than memorising specific examples.",
    distractors: [
      "When an AI system uses too much computing power during training, causing the hardware to overheat and shut down",
      "A safety mechanism that stops an AI from generating outputs above a certain length to prevent excessive server load",
    ] as unknown as [string, string, string],
  },
]

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr]
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}

function makeOptions(term: Term): { text: string; correct: boolean }[] {
  const options = [
    { text: term.correct, correct: true },
    { text: term.distractors[0], correct: false },
    { text: term.distractors[1], correct: false },
  ]
  return shuffle(options)
}

export function JargonMatch() {
  const [terms] = useState<Term[]>(() => shuffle([...TERMS]))
  const [current, setCurrent] = useState(0)
  const [selected, setSelected] = useState<string | null>(null)
  const [scores, setScores] = useState<boolean[]>([])
  const [finished, setFinished] = useState(false)
  const [options, setOptions] = useState<{ text: string; correct: boolean }[]>(() => makeOptions(TERMS[0]))

  const term = terms[current]
  const isAnswered = selected !== null
  const totalCorrect = scores.filter(Boolean).length

  function handleSelect(text: string, correct: boolean) {
    if (isAnswered) return
    setSelected(text)
    setScores((prev) => [...prev, correct])
  }

  function handleNext() {
    if (current < terms.length - 1) {
      const nextIndex = current + 1
      setCurrent(nextIndex)
      setOptions(makeOptions(terms[nextIndex]))
      setSelected(null)
    } else {
      setFinished(true)
    }
  }

  function handleRestart() {
    setCurrent(0)
    setSelected(null)
    setScores([])
    setFinished(false)
    setOptions(makeOptions(terms[0]))
  }

  if (finished) {
    const pct = Math.round((totalCorrect / terms.length) * 100)
    return (
      <div className="min-h-screen bg-gradient-to-b from-emerald-50 to-white dark:from-gray-900 dark:to-gray-950 px-4 py-10 flex flex-col items-center">
        <div className="max-w-lg w-full space-y-6 text-center">
          <div className="text-7xl">&#x1F4AC;</div>
          <h1 className="text-3xl font-bold text-gray-800 dark:text-gray-100">Jargon match complete!</h1>
          <p className="text-xl text-gray-600 dark:text-gray-300">
            You got <span className="font-bold text-emerald-600 dark:text-emerald-400">{totalCorrect} / {terms.length}</span> correct ({pct}%)
          </p>
          <p className="text-gray-500 dark:text-gray-400 text-sm">
            {pct >= 80
              ? 'Excellent — you have a strong grip on AI terminology!'
              : pct >= 50
              ? 'Good effort! Review the explanations for any you missed.'
              : "Nice try — the explanations are a great way to learn these concepts."}
          </p>
          <button
            onClick={handleRestart}
            className="inline-flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white font-semibold px-6 py-3 rounded-xl transition-colors"
          >
            &#x1F504; Play again
          </button>
          <div>
            <a href="#/" className="text-emerald-600 dark:text-emerald-400 text-sm hover:underline">
              Back to home
            </a>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-emerald-50 to-white dark:from-gray-900 dark:to-gray-950 px-4 py-10 flex flex-col items-center">
      <div className="max-w-lg w-full space-y-6">

        <div className="text-center space-y-2">
          <div className="text-5xl">&#x1F4AC;</div>
          <h1 className="text-3xl font-bold text-gray-800 dark:text-gray-100">Jargon match</h1>
          <p className="text-gray-500 dark:text-gray-400 text-sm">
            Question {current + 1} of {terms.length} — pick the best definition
          </p>
          <div className="flex justify-center gap-1.5 pt-1">
            {terms.map((_, i) => (
              <div
                key={i}
                className={`h-2 w-6 rounded-full transition-all ${
                  i < scores.length
                    ? scores[i] ? 'bg-emerald-500' : 'bg-red-400'
                    : i === current
                    ? 'bg-emerald-300'
                    : 'bg-gray-200 dark:bg-gray-700'
                }`}
              />
            ))}
          </div>
        </div>

        <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-sm border border-emerald-100 dark:border-emerald-900 p-6 text-center">
          <p className="text-xs text-emerald-600 dark:text-emerald-400 font-semibold uppercase tracking-wide mb-2">What does this mean?</p>
          <h2 className="text-2xl font-bold text-gray-800 dark:text-gray-100">{term.term}</h2>
        </div>

        <div className="space-y-3">
          {options.map(({ text, correct }) => {
            let color = 'bg-white dark:bg-gray-800 border-gray-200 dark:border-gray-700 text-gray-700 dark:text-gray-200 hover:border-emerald-400 hover:bg-emerald-50 dark:hover:bg-emerald-950'
            if (isAnswered) {
              if (correct) color = 'bg-emerald-100 dark:bg-emerald-900 border-emerald-400 dark:border-emerald-600 text-emerald-800 dark:text-emerald-200'
              else if (selected === text) color = 'bg-red-100 dark:bg-red-900 border-red-400 dark:border-red-600 text-red-800 dark:text-red-200'
              else color = 'bg-gray-50 dark:bg-gray-800 border-gray-200 dark:border-gray-700 text-gray-400 dark:text-gray-500'
            }
            return (
              <button
                key={text}
                onClick={() => handleSelect(text, correct)}
                disabled={isAnswered}
                className={`w-full border-2 rounded-xl p-4 text-left text-sm leading-relaxed transition-all ${color} ${!isAnswered ? 'cursor-pointer' : 'cursor-default'}`}
              >
                {text}
                {isAnswered && correct && <span className="ml-2 text-emerald-600 dark:text-emerald-400 font-bold">&#x2713;</span>}
                {isAnswered && !correct && selected === text && <span className="ml-2 text-red-600 dark:text-red-400 font-bold">&#x2717;</span>}
              </button>
            )
          })}
        </div>

        {isAnswered && (
          <div className="bg-white dark:bg-gray-800 rounded-2xl border border-gray-100 dark:border-gray-700 p-4 space-y-2">
            <p className="font-semibold text-gray-700 dark:text-gray-200 text-sm">
              {scores[scores.length - 1] ? '✓ Correct!' : '✗ Not quite — here is the explanation:'}
            </p>
            <p className="text-gray-500 dark:text-gray-400 text-sm leading-relaxed">{term.explanation}</p>
            <button
              onClick={handleNext}
              className="inline-flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white font-semibold px-5 py-2 rounded-xl transition-colors text-sm mt-1"
            >
              {current < terms.length - 1 ? 'Next term →' : 'See results 🏆'}
            </button>
          </div>
        )}

        <div className="text-center">
          <a href="#/" className="text-emerald-600 dark:text-emerald-400 text-sm hover:underline">
            Back to home
          </a>
        </div>

      </div>
    </div>
  )
}
